---
title: "Ideas"
date: 10/24/18
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ideas

This is a document where we can post our ideas as they occur. Add newest bits to the top.

## Some possibly useful websites showing what others are doing along these lines
[stocksims](https://github.com/datalimited/stocksims) - see simulated dir for some examples of setups (FLR)
[SNAP](https://github.com/SNAPwg/SNAP) - a data limited approach using csv files
[GeMS](https://github.com/szuwalski/GeMS) - a two box spatial model for MSE (see the Wiki)
[DLMtoolkit](https://www.datalimitedtoolkit.org/) - flashy homepage, lots of interesting computing details under the hood
[MSEtool](https://rdrr.io/cran/MSEtool/) - from the makers of DLMtool comes MSEtool - works with analytical assessments instead of data-limited assessments
[PBR-Tier-System](https://github.com/John-Brandon/PBR-Tier-System) - Fortran code for a blast from the past
[mpb](https://github.com/laurieKell/mpb) - Laurie Kell version of MSE for FLR
[FLR MSE](https://github.com/flr/mse) - official FLR version of MSE
[GMSE](https://github.com/ConFooBio/gmse) - a complete package including tests and vignettes
[mseSS](https://github.com/cgrandin/msess) - because everything is better with SS
[tunaMSE](https://puntapps.shinyapps.io/tunamse/) - a Shiny MSE

## Another possible approach to getting project done
Fishackathon! Set aside a day sometime this winter and have folks contribute code. Not sure how to make it into a contest, but I'm sure there is a way. Would require us to have the data dictionary, naming conventions, style, and framework set up in advance. Would require some clean up after the fact to get all the testthat stuff and overall testing done, but would bring together lots of folks interested in using the R package when it is done. Lots of ways to skin this cat...

## Possible approach to getting project done
https://blog.trello.com/beginners-guide-scrum-and-agile-project-management
Mike Palmer has been using this for PTNS and is planning on using it for ADIOS. We could check in with him to see if he thinks it would work for this project.

Some other free software for project management can be found at https://project-management-software.financesonline.com/?s=&pt=applications&field_5404531d2448f=Freelancers&field_540452ed2448e=Free&field_5404529a2448d=English&field_540451352448c=All&field_544e2147b847e=On+Premise where I've already done some filtering.

## Suggestions for organizing functions

read_input_functions.r
- read_ASAP (possibly split this into read_ASAP_dat and read_ASAP_rdat)
- read_VPA
- read_WHThing (or whatever we end up calling the package, this function would read files created by the package)

setup_operating_model_functions.r
- define_dimensions
- define_starting_pop
- define_recruitment
- define_F
- define_selectivity
etc. etc. etc.

setup_estimating_model_functions.r
- create_ASAP
- create_VPA
- create_SAM
- create_WHAM

setup_scenarios_functions.r
- set_scenarios (not sure if this is really needed, placeholder for now)

population_dynamics_functions.r
- apply_survival
- realized_recruitment
- calculate_catch
- generate_indices
- apply_observation_error
- calculate_reference_points
- apply_harvest_control_rule (not sure this goes here)

run_functions.r
- run_one_model
- run_all_models
- run_scenarios

summarizing_functions.r
- make_table_X
- make_plot_Y
(will need lots of these, will need to think how best to organize them once we start producing results)

utility_functions.r (could also call this UsefulFunctions.r)
(lots of the functions Dan has already provided)

What is missing?

## Proposed directory structure

R - directory for the package R code
man - directory for the roxygen-generated documentation (use devtools::document() to create the files)
vignettes - directory for multiple short examples of how to use the package functions efficiently
test - directory for the testthat code to run tests on each piece that we put in the R dir
datadictionary - directory to hold our decisions on structures, naming conventions, styles, etc.
explorations - a test directory for us to show each other code/problems before it goes into the R dir

In the main directory would be: 
DESCRIPTION file (good for keeping track of version)
NAMESPACE (for listing the required packages)
README.md (for others to get an idea of what we're doing) and 
Ideas.Rmd (for us to share our ideas internally). 

Thoughts?

## Testing

R package testthat has been recommended by some
* GitHub site - https://github.com/r-lib/testthat
* Write-up by Hadley Wickham - http://r-pkgs.had.co.nz/tests.html
* Inattentional Coffee blog - https://katherinemwood.github.io/post/testthat/

Travis CI for continuous integration is popular
* Home page - https://travis-ci.org/
* Julia Silge blog - https://juliasilge.com/blog/beginners-guide-to-travis/

Preliminary look at these seems to indicate testthat is the better choice for our purposes. It seems to be set up to evaluate a structured comparison between the return value of a function and what you expect the function to produce. This should work pretty well for our modular design. 

Travis CI seems to be more for testing the version compatibility of dependent libraries.

## Possible names (still thinking of more...)

* WHOM - Woods Hole Operating Model ("whom" pronounced to rhyme with "qualm" as in the Woody Allen movie)
* WHSPR - Woods Hole Simulation Project in R (subtle link to WHAM, who has a song "Careless Whisper")
* SimSAM - Simulator for Stock Assessment Methods (perhaps too close to SISAM)
* WHEEP - Woods Hole Experimenting on Exploited Populations (as in read 'em and)
* WHONDER - Woods Hole Open Numeric Determination of Exploited Resources (as in one hit, but a real stretch on the acronym)


